-- CREATE TABLE USERS(
--     id INT PRIMARY KEY,
--     Name VARCHAR(50) UNIQUE,
--     Email VARCHAR(50) UNIQUE NOT NULL,
--     Password VARCHAR(50) NOT NULL
-- );


ALTER TABLE users
MODIFY id VARCHAR(50) ;


